
### Create a Report
POST http://localhost:3000/reports
content-type: application/json

{
    "price": 1000,
    "make": "Toyota",
    "model": "Corola",
    "year": 1999,
    "lng": 0,
    "lat": 0,
    "mileage": 1000
    
    }