
### Create a Report
POST http://localhost:3000/reports
Content-type: application/json

{
    "price": 300,
    "make": "Seat",
    "model": "Ibiza",
    "year": 1999,
    "lng": 0,
    "lat": 0,
    "mileage": 1000
    
    }

PATCH http://localhost:3000/reports/
Content-Type: application/json

{
    "approved": true
}